config/routes.rb
Rails.application.routes.draw do

	root to: 'page_statics#index'
	devise_for :users
	resources :items do
		resources :pictures, only: [:create, :new]
	end

	resources :cart_elements, only: [:destroy, :update, :create]

	resources :users, :path => "mon_profil" do
		resources :carts, :path => "mon_panier"
	end

	namespace :admin do
		root to: 'admin#index'
		resources :users, :charges, :orders, :carts, :items
	end

	resources :orders, :path => "mes_commandes"
	resources :charges
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
  has_many :ordered_items
  has_many :items, through: :ordered_items
       
  after_create :order_send
  after_create :admin_send
  def order_send
    OrderMailer.order_email(self).deliver_now
  end

  def admin_send
    OrderMailer.admin_email(self).deliver_now
  end
end

app/controllers/admin/orders_controller.rb
module Admin

	class OrdersController < ApplicationController
		before_action :check_if_admin


		def index
			@orders = Order.all

		end

		def show
			@order = Order.find(params[:id])
			@ordered_items = OrderedItem.where(order_id: @order.id)
			@purchases = []
			@amount = 0
			@ordered_items.each do |item|
				@purchases << Item.find(item.item_id)
				@amount += Item.find(item.item_id).price * item.quantity
			end
		end

		def new
		end

		def create
			@order = Order.create
		end

		def edit
		end

		def update
		end

		def destroy
		end

		private

		def check_if_admin
			if current_user.admin == false
				flash[:notice] = "Must be admin"
				redirect_to root_path
			end
		end

		def sell_value
			@ordered_items = OrderedItem.find_by(order_id: order.id)
			@amount = 0
			@ordered_items.each do |item|
				@amount += Item.find(item.item_id).price * item.quantity
			end
			return @amount
		end
	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :authenticate_user!, only: [:index, :show, :edit, :update, :destroy]


	def index
		@user = current_user
		@orders = Order.where(user_id: @user.id)
	end

	def show
		@order = Order.find(params[:id])
		@ordered_items = OrderedItem.where(order_id: @order.id)
		@purchases = []
		@amount = 0
		@ordered_items.each do |item|
			@purchases << Item.find(item.item_id)
			@amount += Item.find(item.item_id).price * item.quantity
		end
	end

	def new
	end

	def create
		@order = Order.create
	end

	def edit
	end

	def update
	end

	def destroy
	end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="using-border py-3">
  <div class="inner_breadcrumb  ml-4">
    <ul class="short_ls">
      <li>
        <%= link_to "dashboard", admin_root_path()%>
        <span>/ /</span>
      </li>
      <li>Orders</li>
    </ul>
  </div>
</div>

<section class="checkout py-lg-4 py-md-3 py-sm-3 py-3">
  <div class="container py-lg-5 py-md-4 py-sm-4 py-3">
    <table class="table">
      <tr>
        <th scope="col">id</th>
        <th scope="col">User</th>
        <th scope="col">Created at</th>
        <th scope="col">Value</th>
        <th scope="col"></th>
      </tr>
      <tbody>
        <% @orders.each do |order|%>
        <tr>
          <td><%= order.id %></td>
          <td><%= order.user_id %></td>
          <td><%= order.created_at.strftime("Recorded: %d/%m/%Y")  %></td>
          <td>
            <% ordered_items = OrderedItem.where(order_id: order.id) %>
            <% amount = 0 %>
            <% ordered_items.each do |item| %>
            <% amount += Item.find(item.item_id).price * item.quantity %>
            <% end %>
            <%= amount %> €
          </td>           
          <td><%= link_to "See More", admin_order_path(order.id), style: 'color:#ff3b9f' %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </section>

app/views/admin/orders/show.html.erb
<div class="using-border py-3">
  <div class="inner_breadcrumb  ml-4">
    <ul class="short_ls">
      <li>
        <%= link_to "dashboard", admin_root_path()%>
        <span>/ /</span>
      </li>
      <li>Order</li>
    </ul>
  </div>
</div>

<section class="checkout py-lg-4 py-md-3 py-sm-3 py-3">
  <div class="container py-lg-5 py-md-4 py-sm-4 py-3">
    <div class="shop_inner_inf">
      <div class="privacy about">
        <h3>Order</h3>
        <div class="checkout-right">
          <h4>Order n°<%= @order.id %>, from user n°<%= @order.user_id %> contained:</h4>
          <table class="timetable_sub">

            <thead>
              <tr>
                <th>SL No.</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Product Name</th>
                <th>Price</th>
              </tr>
            </thead>

            <tbody>
              <% i=0 %>
              <% @purchases.each do |item|%>
              <tr class="rem1">
                <td class="invert"><%= i += 1 %></td>
                <td class="invert"><%= item.id %></td>
                <td class="invert"><%= @ordered_items[(i - 1)].quantity %></td>
                <td class="invert"><%= item.title %></td>
                <td class="invert"><%= item.price %></td>
              <% end %>
            </tbody>
          </table>
        
        <div class="checkout-left">
          <div class="col-md-4 checkout-left-basket">              
            <ul>
              <li>Total <i>-</i> <span><%= @amount %> €</span></li>
            </ul>
          </div>
        </div>
</div>
      </div>
    </div>
  </div>
</section>