config/routes.rb
Rails.application.routes.draw do

	root to: 'page_statics#index'
	devise_for :users
	resources :items do
		resources :pictures, only: [:create, :new]
	end

	resources :cart_elements, only: [:destroy, :update, :create]

	resources :users, :path => "mon_profil" do
		resources :carts, :path => "mon_panier"
	end

	namespace :admin do
		root to: 'admin#index'
		resources :users, :charges, :orders, :carts, :items
	end

	resources :orders, :path => "mes_commandes"
	resources :charges
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_one :user
	has_many :cart_elements
	has_many :items, through: :cart_elements
end

app/controllers/admin/carts_controller.rb
module Admin

  class CartsController < ApplicationController
    before_action :check_if_admin

    def index
      @carts = Cart.all
    end

    def new
      @cart = Cart.new
    end
    
    def create
      @user = current_user
      @item = Item.find(params[:item_id])
      @cart = Cart.create(user: current_user)
      CartElement.create(cart: @cart, item_id: @item.id, quantity: 1)
      redirect_to items_path
    end

    def show      
      @cart = Cart.find(params[:id])
      @cart_items = CartElement.where(cart_id: @cart.id)
      @items = []
      @amount = 0
      @cart_items.each do |item|
        @items << Item.find(item.item_id)
        @amount += Item.find(item.item_id).price * item.quantity
      end
    end

    def update
      @cart = Cart.find(params[:id])
    end

    def destroy
      @cart = Cart.find(params[:id])
      @cart.destroy
    end

    private

    def check_if_admin
      if current_user.admin == false
        flash[:notice] = "Must be admin"
        redirect_to root_path
      end
    end

  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :authenticate_user!, only: [:index, :show, :edit, :update, :destroy]
  before_action :check_cart, only: [:index, :show, :edit, :update, :destroy]

  def new
    @cart = Cart.new
  end
  
  def create
    @user = current_user
    @item = Item.find(params[:item_id])
    @cart = Cart.create(user: current_user)
    CartElement.create(cart: @cart, item_id: @item.id, quantity: 1)
    redirect_to items_path
  end

  def show    
    @user = current_user
    @cart = Cart.find_by(user_id: @user.id)
    @cart_items = CartElement.where(cart_id: @cart.id)
    @items = []
    @amount = 0
    @cart_items.each do |item|
      @items << Item.find(item.item_id)
      @amount += Item.find(item.item_id).price * item.quantity
    end
  end

  def update
    @cart = Cart.find(params[:id])
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy
  end

  private
  
  def check_cart
    if current_user.id != Cart.find(params[:id]).user_id
      flash[:notice] = "You can't see that."
      redirect_to root_path
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/index.html.erb
<!-- banner -->
<div class="inner_page-banner one-img">
</div>
<!-- short -->
        <br><br>
        <div class="using-border py-3">
            <div class="inner_breadcrumb  ml-4">
                <ul class="short_ls">
                <li><h4>checkout Zone</h4></li>
                </ul>
            </div>
        </div>
        <br><br>
<!-- //short-->
<!--Checkout-->  
<!-- //banner -->
<!-- top Products -->

<section class="checkout py-lg-4 py-md-3 py-sm-3 py-3">
  <div class="container py-lg-5 py-md-4 py-sm-4 py-3">
      <div class="shop_inner_inf">
        <div class="privacy about">
            <h3>Chec<span>kout</span></h3>
            <div class="checkout-right">
              <h4>Your shopping cart contains: <span>3 Products</span></h4>
              <table class="timetable_sub">
                  <thead>
                    <tr>
                        <th>SL No.</th>
                        <th>Product</th>
                        <th>Quality</th>
                        <th>Product Name</th>
                        <th>Price</th>
                        <th>Remove</th>
                    </tr>
                  </thead>
                  <tbody>



                    <tr class="rem1">
                        <td class="invert">1</td>
                        <td class="invert-image"><a href="single.html"><img src="images/f1.jpg" alt=" " class="img-responsive"></a></td>
                        <td class="invert">
                          <div class="quantity">
                              <div class="quantity-select">
                                <div class="entry value-minus">&nbsp;</div>
                                <div class="entry value"><span>1</span></div>
                                <div class="entry value-plus active">&nbsp;</div>
                              </div>
                          </div>
                        </td>
                        <td class="invert">Bella Toes</td>
                        <td class="invert">$675.00</td>
                        <td class="invert">
                          <div class="rem">
                              <div class="close1"> </div>
                          </div>
                        </td>
                    </tr>



                  </tbody>
              </table>
            </div>
            <div class="checkout-left">
              <div class="col-md-4 checkout-left-basket">
                  <h4>Continue to basket</h4>
                  <ul>



                    <li>Product1 <i>-</i> <span>$675.00 </span></li>


                    <li>Total Service Charges <i>-</i> <span>$55.00</span></li>
                    <li>Total <i>-</i> <span>$1405.00</span></li>




                  </ul>
              </div>
              <div class="col-md-8 address_form">
                  <h4>Add a new Details</h4>
                  <form action="payment.html" method="post" class="creditly-card-form agileinfo_form">
                    <section class="creditly-wrapper wrapper">
                        <div class="information-wrapper">
                          <div class="first-row form-group">
                              <div class="controls">
                                <label class="control-label">Full name: </label>
                                <input class="billing-address-name form-control" type="text" name="name" placeholder="Full name">
                              </div>
                              <div class="card_number_grids">
                                <div class="card_number_grid_left">
                                    <div class="controls">
                                      <label class="control-label">Mobile number:</label>
                                      <input class="form-control" type="text" placeholder="Mobile number">
                                    </div>
                                </div>
                                <div class="card_number_grid_right">
                                    <div class="controls">
                                      <label class="control-label">Landmark: </label>
                                      <input class="form-control" type="text" placeholder="Landmark">
                                    </div>
                                </div>
                                <div class="clear"> </div>
                              </div>
                              <div class="controls">
                                <label class="control-label">Town/City: </label>
                                <input class="form-control" type="text" placeholder="Town/City">
                              </div>
                              <div class="controls">
                                <label class="control-label">Address type: </label>
                                <select class="form-control option-w3ls">
                                    <option>Office</option>
                                    <option>Home</option>
                                    <option>Commercial</option>
                                </select>
                              </div>
                          </div>
                          <button class="submit check_out">Delivery to this Address</button>
                        </div>
                    </section>
                  </form>
                  <div class="checkout-right-basket">
                    <a href="payment.html">Make a Payment </a>
                  </div>
              </div>
              <div class="clearfix"> </div>
              <div class="clearfix"></div>
            </div>
        </div>
      </div>
      <!-- //top products -->
  </div>
</section>



      <!-- Nombre d'articles -->
<%= @cart_items.length%>

<!-- Iteration sur les articles du panier-->
<% @items.each_with_index do |item, i|%>
  <!-- Pour item n°x -->
  <%= i+1 %>
  <%= item.title%>
  <%= item.price%>
<% end %>

app/views/carts/show.html.erb
<!-- short -->
        <br><br>
        <div class="using-border py-3">
            <div class="inner_breadcrumb  ml-4">
                <ul class="short_ls">
                <li><h4>Checkout Zone</h4></li>
                </ul>
            </div>
        </div>
        <br><br>
<!-- //short-->

<section class="checkout py-lg-4 py-md-3 py-sm-3 py-3">
  <div class="container py-lg-5 py-md-4 py-sm-4 py-3">
    <div class="shop_inner_inf">
      <div class="privacy about">
        <h3>Checkout</h3>
        <div class="checkout-right">
          <h4>Your shopping cart contains:</h4>
          <table class="timetable_sub">

            <thead>
              <tr>
                <th>SL No.</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Product Name</th>
                <th>Price</th>
                <th>Remove</th>
              </tr>
            </thead>

            <tbody>
              <% i=0 %>
              <% @cart_items.each_with_index do |item, index|%>
              <tr class="rem1">
                <td class="invert"><%= i += 1 %></td>
                <% if @items[index].picture.attached? == true%>
									  <div class="thumb-image"> <%= image_tag @items[index].picture, alt: 'picture' %> data-imagezoom="true" class="img-fluid" alt=" "> </div>
									<% else %>
									  <td class="invert-image"><img src=<%= @items[index].image_url %>, class="card-img-top" alt="..."></td>
									<% end %>
                <td class="invert">
                  <div class="quantity">
                    <div class="quantity-select">
                      <%= link_to cart_element_path(cart_elem_id: @cart_items[index].id, quantity: -1), method: :put do%>
                      <div class="entry value-minus">&nbsp;</div>
                      <% end %>
                      <div class="entry value"><span><%= item.quantity %></span></div>
                      <%= link_to cart_element_path(cart_elem_id: @cart_items[index].id, quantity: 1), method: :put do%>
                      <div class="entry value-plus active">&nbsp;</div>
                      <% end %>
                    </div>
                  </div>
                </td>
                <td class="invert"><%= @items[index].title %></td>
                <td class="invert"><%= @items[index].price %></td>
                <td class="invert">
                  <%= link_to cart_element_path(cart_elem_id: @cart_items[index].id), method: :delete do %>
                  <%= content_tag :span, "", :class => "far fa-trash-alt", style: 'color:#000000' %>
                  <% end %>
                </td>
              </tr>
              <% end %>
            </tbody>

          </table>
        </div>

        <div class="col-md-8 address_form">
          <h4>Your delivery adress is: <%= current_user.email %></h4>
          <form action="payment.html" method="post" class="creditly-card-form agileinfo_form">
            <section class="creditly-wrapper wrapper">
              <div class="information-wrapper">
                <div class="first-row form-group">
                  <div class="controls">
                    <label class="control-label">Change your delivery adress (optional): </label>
                    <input class="billing-address-name form-control" type="text" name="name" placeholder="New email adress">
                  </div>
                  <button class="submit check_out"><%= link_to "Delivery to this Address", root_path %></button>
                </div>
              </section>
            </form>
          </div>

          <div class="checkout-left">
            <div class="col-md-4 checkout-left-basket">
              <h4><%= link_to "Pay now", new_charge_path %></h4>                  
              <ul>
                <li>Total <i>-</i> <span><%= @amount %> €</span></li>
              </ul>
            </div>
          </div>
        </section>
      </form>
    </div>
  </div>
</div>
<div class="clearfix"> </div>
<div class="clearfix"></div>
</div>
</section>
</br>