config/routes.rb
Rails.application.routes.draw do

	root to: 'page_statics#index'
	devise_for :users
	resources :items do
		resources :pictures, only: [:create, :new]
	end

	resources :cart_elements, only: [:destroy, :update, :create]

	resources :users, :path => "mon_profil" do
		resources :carts, :path => "mon_panier"
	end

	namespace :admin do
		root to: 'admin#index'
		resources :users, :charges, :orders, :carts, :items
	end

	resources :orders, :path => "mes_commandes"
	resources :charges
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :ordered_items
  has_many :orders, through: :ordered_items
  has_many :cart_elements
  has_many :carts, through: :cart_elements
  has_one_attached :picture

  validates :title,
    presence: true,
    uniqueness: true

  validates :image_url,
    presence: true,
    uniqueness: true,
    format: { with: /\A[h]t{2}[p]s?[:]\/{2}(\S+)[.](\D{2,3})\/\S*/ }

  validates :description,
    presence: true

  validates :price,
    presence: true,
    numericality: true
end

app/controllers/admin/items_controller.rb
module Admin

  class ItemsController < ApplicationController
    before_action :check_if_admin

    def new
      @item = Item.new
    end

    def create
      permited_params = params.require().permit(:title, :price, :description, :image_url)
      @item = Item.new(permited_params)

      if @item.save
        flash[:success] = "Item created"
        redirect_to root_path
      else 
        render 'new'
      end
    end

    def index
      @items = Item.all
    end

    def show
      @item = Item.find(params[:id])

    end

    def update
    # Waiting for forms
    #permited_params = params.require().permit(:title, :price, :description, :image_url)
    @item = Item.find(params[:id])
    @item.update(permited_params)
    redirect_to item_path(params[:id])
    end

    def destroy
      @item = Item.find(params[:id])
    end

    private

    def check_if_admin
      if current_user.admin == false
        flash[:notice] = "Must be admin"
        redirect_to root_path
      end
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def new
    @item = Item.new
  end

  def create
    permited_params = params.require().permit(:title, :price, :description, :image_url)
    @item = Item.new(permited_params)

    if @item.save
      flash[:success] = "Item created"
      redirect_to root_path
    else 
      render 'new'
    end
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    
  end

  def update
    # Waiting for forms
    #permited_params = params.require().permit(:title, :price, :description, :image_url)
    @item = Item.find(params[:id])
    @item.update(permited_params)
    redirect_to item_path(params[:id])
  end

  def destroy
    @item = Item.find(params[:id])
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<!-- short -->
<br><br>
<div class="using-border py-3">
    <div class="inner_breadcrumb  ml-4">
        <ul class="short_ls">
            <li><h4>Shop Now</h4></li>
        </ul>
    </div>
</div>
<br><br>
<!-- //short-->
<div class="container">
    <div class="card-columns">
        <% @items.each do |item| %>
        <div class="card">
            <% if item.picture.attached? == false%>
            <img src=<%= item.image_url %> class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title"><%= item.title %></h5>
                <p class="card-text"><%= item.price %>€ <del>99,99€</del></p>
            </div>
            <div class="card-footer text-center">
                <button type="submit" class="toys-cart ptoys-cart add">
                  <% if user_signed_in?%>
                    <%= link_to "Add to cart", cart_elements_path(cart_id: current_user.cart.id, item_id: item.id), method: :post %>
                  <% end %>
                </button>
                <hr>
                <button type="submit" class="toys-cart ptoys-cart add">
                    <%= link_to "More details", item_path(item.id) %>
                </button>
                <% else %>
                <%= image_tag item.picture, alt: 'picture', class: "card-img-top" %>
                <% end %>
            </div>
        </div>
        <br>
        <br>
        <% end %>
    </div>
</div>        
<br>

app/views/items/show.html.erb
<div class="using-border py-3">
	<div class="inner_breadcrumb  ml-4">
		<ul class="short_ls">
			<li><h4>Pics Station // <%= @item.title %></h4></li>
		</ul>
	</div>
</div>
<!-- //short-->
<!--//banner -->
<!--/shop-->
<section class="banner-bottom py-lg-5 py-3">
	<div class="container">
		<div class="inner-sec-shop pt-lg-4 pt-3">
			<div class="row">
				<div class="col-lg-4 single-right-left ">
					<div class="grid images_3_of_2">
						<div class="flexslider1">
							<ul class="slides">
								<li data-thumb="images/f2.jpg">
									<% if @item.picture.attached? == true%>
									<div class="thumb-image"> <%= image_tag @item.picture, alt: 'picture' %> data-imagezoom="true" class="img-fluid" alt=" "> </div>
									<% else %>
									<img src="<%= @item.image_url %>" class="card-img-top">
									<% end %>
								</li>
							</ul>
							<div class="clearfix"></div>
						</div>
					</div>
				</div>
				<div class="col-lg-8 single-right-left simpleCart_shelfItem">
					<h3><%= @item.title %></h3>
					<p><span class="item_price"><%= @item.price %>€</span>
						<del>99,99€</del>
					</p>
					<div class="occasion-cart">
						<div class="toys single-item singlepage">
							<form action="#" method="post">
								<button type="submit" class="toys-cart-2 ptoys-cart add">
                <% if user_signed_in?%>
									<%= link_to "Add to cart", cart_elements_path(cart_id: current_user.cart.id, item_id: @item.id), method: :post %>
                <% end %>
								</button>
							</form>
							<% if current_user != nil && current_user.admin? == true %>
							<button class="btn btn-primary" type="button"><%= link_to "edit picture", new_item_picture_path(params[:id])%></button>
							<% else %>
							<% end %>
						</div>
					</div>
				</div>
				<div class="clearfix"> </div>
				<br>
				<br>
				<!--/tabs-->
				<div class="responsive_tabs">
					<div id="horizontalTab">
						<br>
						<ul class="resp-tabs-list">
							<li>Description</li>
						</ul>
						<div class="resp-tabs-container">
							<!--/tab_one-->
							<div class="tab1">
								<div class="single_page text-justify">
									<h6><%= @item.title %></h6>
									<hr>
									<p><%= @item.description %>
									</p>
								</div>
							</div>
							<!--//tab_one-->
						</div>
					</div>
				</div>
				<!--//tabs-->
			</div>
		</div>
	</div>
</section>
<br>
<br>