config/routes.rb
Rails.application.routes.draw do

	root to: 'page_statics#index'
	devise_for :users
	resources :items do
		resources :pictures, only: [:create, :new]
	end

	resources :cart_elements, only: [:destroy, :update, :create]

	resources :users, :path => "mon_profil" do
		resources :carts, :path => "mon_panier"
	end

	namespace :admin do
		root to: 'admin#index'
		resources :users, :charges, :orders, :carts, :items
	end

	resources :orders, :path => "mes_commandes"
	resources :charges
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_one :user
	has_many :cart_elements
	has_many :items, through: :cart_elements
end

app/models/cart_element.rb
class CartElement < ApplicationRecord
	belongs_to :cart
	has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :ordered_items
  has_many :orders, through: :ordered_items
  has_many :cart_elements
  has_many :carts, through: :cart_elements
  has_one_attached :picture

  validates :title,
    presence: true,
    uniqueness: true

  validates :image_url,
    presence: true,
    uniqueness: true,
    format: { with: /\A[h]t{2}[p]s?[:]\/{2}(\S+)[.](\D{2,3})\/\S*/ }

  validates :description,
    presence: true

  validates :price,
    presence: true,
    numericality: true
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
  has_many :ordered_items
  has_many :items, through: :ordered_items
       
  after_create :order_send
  after_create :admin_send
  def order_send
    OrderMailer.order_email(self).deliver_now
  end

  def admin_send
    OrderMailer.admin_email(self).deliver_now
  end
end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
	belongs_to :order
	has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  after_create :cart_create
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :cart
  has_many :orders
	has_many :ordered_items, through: :orders
	# has_many :items, through: :cart
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def cart_create
    Cart.create(user_id: self.id)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :authenticate_user!, only: [:index, :show, :edit, :update, :destroy]
  before_action :check_cart, only: [:index, :show, :edit, :update, :destroy]

  def new
    @cart = Cart.new
  end
  
  def create
    @user = current_user
    @item = Item.find(params[:item_id])
    @cart = Cart.create(user: current_user)
    CartElement.create(cart: @cart, item_id: @item.id, quantity: 1)
    redirect_to items_path
  end

  def show    
    @user = current_user
    @cart = Cart.find_by(user_id: @user.id)
    @cart_items = CartElement.where(cart_id: @cart.id)
    @items = []
    @amount = 0
    @cart_items.each do |item|
      @items << Item.find(item.item_id)
      @amount += Item.find(item.item_id).price * item.quantity
    end
  end

  def update
    @cart = Cart.find(params[:id])
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy
  end

  private
  
  def check_cart
    if current_user.id != Cart.find(params[:id]).user_id
      flash[:notice] = "You can't see that."
      redirect_to root_path
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def new
    @item = Item.new
  end

  def create
    permited_params = params.require().permit(:title, :price, :description, :image_url)
    @item = Item.new(permited_params)

    if @item.save
      flash[:success] = "Item created"
      redirect_to root_path
    else 
      render 'new'
    end
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    
  end

  def update
    # Waiting for forms
    #permited_params = params.require().permit(:title, :price, :description, :image_url)
    @item = Item.find(params[:id])
    @item.update(permited_params)
    redirect_to item_path(params[:id])
  end

  def destroy
    @item = Item.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:index, :show, :edit, :update, :destroy]
	before_action :is_admin?, only: [:index]
	before_action :check_user, only: [:index, :show, :edit, :update, :destroy]


	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
	end

	def create
	end

	def edit
	end

	def update
	end

	def destroy
	end
	
	private

	def is_admin?
		if !current_user.nil? && current_user.admin = true
			return true
			flash[:notice] = "You can't access admins' pages."
		end
	end

	def check_user
		if current_user.id != User.find(params[:id]).id
			flash[:notice] = "You can't see that."
			redirect_to root_path
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for_flash(type)
    case type
      when 'notice' then "alert-info"
      when 'success' then "alert-success"
      when 'danger' then "alert-danger"
      when 'warning' then "alert-warning"
    end
  end
end

app/helpers/cart_elements_helper.rb
module CartElementsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/ordered_items_helper.rb
module OrderedItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/page_statics_helper.rb
module PageStaticsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/admin/index.html.erb
<div class="using-border py-3">
  <div class="inner_breadcrumb  ml-4">
    <ul class="short_ls">
      <li>
        <%= link_to "dashboard", admin_root_path()%>
        <span>/ /</span>
      </li>
      <li>Key Performance Indicators</li>
    </ul>
  </div>
</div>

<section class="checkout py-lg-4 py-md-3 py-sm-3 py-3">
  <div class="container py-lg-5 py-md-4 py-sm-4 py-3">
    <table class="table">

      <tbody>
        <tr>
          <th scope="row">Users</th>
          <td><%= @nb_users %></td>          
          <td><%= link_to "See More", admin_users_path, style: 'color:#ff3b9f' %></td>
        </tr>
        <tr>
          <th scope="row">Items</th>
          <td><%= @nb_items%></td>          
          <td><%= link_to "See more", admin_items_path, style: 'color:#ff3b9f' %></td>
        </tr>
        <tr>
          <th scope="row">Orders</th>
          <td><%= @nb_orders %></td>          
          <td><%= link_to "See more", admin_orders_path, style: 'color:#ff3b9f' %></td>
        </tr>
        <tr>
          <th scope="row">Temporary Carts in value</th>
          <td><%= @carts_value %> €</td>          
          <td><%= link_to "See more", admin_carts_path, style: 'color:#ff3b9f' %></td>
        </tr>
        <tr>
          <th scope="row">Total sells</th>
          <td><%= @amount_sells %> €</td>          
          <td><%= link_to "See more", admin_orders_path, style: 'color:#ff3b9f' %></td>
        </tr>
      </tbody>
    </table>
  </div>
</section>